jest.mock('@react-native-async-storage/async-storage',()=>{const data=new Map<string,string>();return{__esModule:true,default:{getItem:jest.fn(async(k:string)=>data.get(k)??null),setItem:jest.fn(async(k:string,v:string)=>{data.set(k,v)}),clear:async()=>data.clear()}}});
jest.mock('../flags',()=>({isFlagEnabled:jest.fn(async()=>true)}));
jest.mock('../../modules/palate-visit-monitor',()=>({isVisitMonitorAvailable:true,PalateVisitMonitor:{startMonitoring:jest.fn(),stopMonitoring:jest.fn(),authorizationStatus:jest.fn(()=> 'always')}}));
let api:any,store:any,flag:any,native:any;
const KEY='palate.passive.optIn',AT='palate.passive.optInAt';
function deferred(){let resolve!:(x?:any)=>void;const promise=new Promise<any>(r=>resolve=r);return{resolve,promise}}
beforeEach(()=>{jest.resetModules();api=require('../passive-capture');store=require('@react-native-async-storage/async-storage').default;flag=require('../flags').isFlagEnabled;native=require('../../modules/palate-visit-monitor').PalateVisitMonitor});
async function flagPending(){await store.setItem(KEY,'1');const entered=deferred(),release=deferred();flag.mockImplementationOnce(()=>{entered.resolve();return release.promise});const start=api.resumePassiveCaptureIfOptedIn();await entered.promise;return{start,release}}
test('direct start cannot bypass absent consent',async()=>{expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({started:false,reason:'not-opted-in'});expect(native.startMonitoring).not.toHaveBeenCalled();expect(flag).not.toHaveBeenCalled()});
test.each(['','true','garbage'])('corrupt consent %s rejects before flag/native',async value=>{await store.setItem(KEY,value);await expect(api.startPassiveCaptureIfEnabled()).rejects.toThrow();expect(flag).not.toHaveBeenCalled();expect(native.startMonitoring).not.toHaveBeenCalled()});
test('unavailable consent rejects before start',async()=>{store.getItem.mockRejectedValueOnce(Error('storage'));await expect(api.resumePassiveCaptureIfOptedIn()).rejects.toThrow();expect(native.startMonitoring).not.toHaveBeenCalled()});
test('opt-out cancels flag-pending resume',async()=>{const{start,release}=await flagPending();await api.optOutOfPassiveCapture();release.resolve(true);expect(await start).toMatchObject({started:false});expect(native.startMonitoring).not.toHaveBeenCalled();expect(await store.getItem(KEY)).toBe('0')});
test('failed off persistence still stops immediately and blocks later starts',async()=>{const{start,release}=await flagPending();store.setItem.mockRejectedValueOnce(Error('disk'));const off=api.optOutOfPassiveCapture();void off.catch(()=>{});expect(native.stopMonitoring).toHaveBeenCalledTimes(1);await expect(off).rejects.toThrow('disk');release.resolve(true);expect(await start).toMatchObject({started:false});expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({started:false});expect(native.startMonitoring).not.toHaveBeenCalled()});
test('off persistence does not wait for pending flag',async()=>{const{start,release}=await flagPending();await api.optOutOfPassiveCapture();expect(await store.getItem(KEY)).toBe('0');release.resolve(true);await start});
test('native stop rejection still persists off and surfaces failure',async()=>{await store.setItem(KEY,'1');native.stopMonitoring.mockImplementationOnce(()=>{throw Error('native stop')});await expect(api.optOutOfPassiveCapture()).rejects.toThrow('native stop');expect(await store.getItem(KEY)).toBe('0');expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({started:false})});
test('pending enable write cannot overwrite later off intent',async()=>{const entered=deferred(),release=deferred(),set=store.setItem.getMockImplementation();store.setItem.mockImplementationOnce(async(k:string,v:string)=>{entered.resolve();await release.promise;await set(k,v)});const on=api.setPassiveOptIn(true);await entered.promise;const off=api.optOutOfPassiveCapture();release.resolve();await Promise.all([on,off]);expect(await store.getItem(KEY)).toBe('0');expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({started:false})});
test('off then explicit on is serialized and permits a fresh start only',async()=>{const{start,release}=await flagPending();await api.optOutOfPassiveCapture();await api.setPassiveOptIn(true);release.resolve(true);expect(await start).toMatchObject({started:false});expect(await api.startPassiveCaptureIfEnabled()).toEqual({started:true});expect(native.startMonitoring).toHaveBeenCalledTimes(1)});
test('debug stop invalidates already pending start without revoking persisted consent',async()=>{const{start,release}=await flagPending();api.stopPassiveCapture();release.resolve(true);expect(await start).toMatchObject({started:false});expect(await store.getItem(KEY)).toBe('1');expect(await api.startPassiveCaptureIfEnabled()).toEqual({started:true})});
test('timestamp failure leaves stored consent visible but runtime startup blocked',async()=>{const set=store.setItem.getMockImplementation();store.setItem.mockImplementation(async(k:string,v:string)=>{if(k===AT)throw Error('timestamp');await set(k,v)});await expect(api.setPassiveOptIn(true)).rejects.toThrow();expect(await api.readPassiveOptInForStatus()).toBe(true);expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({started:false});expect(native.startMonitoring).not.toHaveBeenCalled()});
test('first timestamp retained through opt-out and re-enable',async()=>{await store.setItem(AT,'12345');await api.setPassiveOptIn(true);await api.optOutOfPassiveCapture();await api.setPassiveOptIn(true);expect(await store.getItem(AT)).toBe('12345');expect(await api.startPassiveCaptureIfEnabled()).toEqual({started:true})});
test('flag off stops and permission absent refuses',async()=>{await store.setItem(KEY,'1');flag.mockResolvedValueOnce(false);expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({reason:'flag-off'});expect(native.stopMonitoring).toHaveBeenCalled();native.authorizationStatus.mockReturnValue('whenInUse');expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({reason:'no-always-permission'});expect(native.startMonitoring).not.toHaveBeenCalled()});
test('failed enable write can recover through a fresh explicit enable',async()=>{store.setItem.mockRejectedValueOnce(Error('disk'));await expect(api.setPassiveOptIn(true)).rejects.toThrow();await api.setPassiveOptIn(true);expect(await api.startPassiveCaptureIfEnabled()).toEqual({started:true})});
