import React from 'react';
const {create, act} = require('react-test-renderer');
import Intro from '../../app/passive-capture-intro';
import WhyLocation from '../../app/onboarding/why-location';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {isFlagEnabled} from '../flags';
import {setPassiveOptIn} from '../passive-capture';
import {Linking} from 'react-native';
import {ensureNotificationPermission} from '../notifications';
const mockBack=jest.fn(), mockReplace=jest.fn(); let mockFocus=true;
jest.mock('expo-router',()=>({useRouter:()=>({back:mockBack,replace:mockReplace,push:jest.fn()}),useLocalSearchParams:()=>({next:'/onboarding/done'}),useFocusEffect:(cb:any)=>require('react').useEffect(()=>mockFocus?cb():undefined,[cb,mockFocus])}));
jest.mock('react-native',()=>({View:'View',ScrollView:'ScrollView',Pressable:'Pressable',StyleSheet:{create:(v:any)=>v},Alert:{alert:jest.fn()},Linking:{openSettings:jest.fn(async()=>{})}}));
jest.mock('react-native-safe-area-context',()=>({SafeAreaView:'SafeAreaView'}));
jest.mock('../../components/Text',()=>({Text:'Text'}));
jest.mock('../../components/Button',()=>({Button:'Button',Spacer:()=>null}));
jest.mock('../../theme',()=>({colors:{},spacing:{},type:{}}));
jest.mock('../analytics',()=>({track:jest.fn()}));
jest.mock('../flags',()=>({isFlagEnabled:jest.fn(async()=>true)}));
jest.mock('../notifications',()=>({ensureNotificationPermission:jest.fn(async()=>false)}));
jest.mock('../../modules/palate-visit-monitor',()=>({isVisitMonitorAvailable:true,PalateVisitMonitor:{authorizationStatus:jest.fn(()=> 'always'),startMonitoring:jest.fn(),stopMonitoring:jest.fn()}}));
jest.mock('expo-location',()=>({getForegroundPermissionsAsync:jest.fn(async()=>({status:'granted'})),getBackgroundPermissionsAsync:jest.fn(async()=>({status:'granted'})),requestForegroundPermissionsAsync:jest.fn(async()=>({status:'denied'})),requestBackgroundPermissionsAsync:jest.fn(async()=>({status:'denied',canAskAgain:false}))}));
Object.defineProperty(globalThis,'fetch',{configurable:true,value:()=>{throw Error('Network forbidden')}});
const native=jest.requireMock('../../modules/palate-visit-monitor');
const originalGet=(AsyncStorage.getItem as jest.Mock).getMockImplementation()!;
const originalSet=(AsyncStorage.setItem as jest.Mock).getMockImplementation()!;
let tree:any;
const deferred=()=>{let resolve!:(v?:any)=>void;const promise=new Promise(r=>resolve=r);return{promise,resolve}};
const text=()=>JSON.stringify(tree.toJSON());
const button=(title:string)=>tree.root.findAllByType('Button').find((b:any)=>b.props.title===title);
const enable=()=>button('Enable background suggestions')||button('Enable passive logging');
async function flush(){await act(async()=>{for(let i=0;i<25;i++)await Promise.resolve()})}
async function mount(){await act(async()=>{tree=create(<Intro/>)});await flush()}
async function press(b:any){await act(async()=>{await b.props.onPress()});await flush()}
async function focus(v:boolean){mockFocus=v;await act(async()=>tree.update(<Intro/>));await flush()}
beforeEach(async()=>{jest.clearAllMocks();(AsyncStorage.getItem as jest.Mock).mockReset().mockImplementation(originalGet);(AsyncStorage.setItem as jest.Mock).mockReset().mockImplementation(originalSet);await setPassiveOptIn(false);await AsyncStorage.clear();jest.clearAllMocks();native.isVisitMonitorAvailable=true;native.PalateVisitMonitor.authorizationStatus.mockReturnValue('always');native.PalateVisitMonitor.startMonitoring.mockReset();(isFlagEnabled as jest.Mock).mockReset().mockResolvedValue(true);(ensureNotificationPermission as jest.Mock).mockReset().mockResolvedValue(false);(Linking.openSettings as jest.Mock).mockReset().mockResolvedValue(undefined);const loc=jest.requireMock('expo-location');loc.getForegroundPermissionsAsync.mockResolvedValue({status:'granted'});loc.getBackgroundPermissionsAsync.mockResolvedValue({status:'granted'});mockFocus=true});
afterEach(async()=>{if(tree)await act(async()=>tree.unmount());tree=null});
test('successful native start is qualified, notification denial does not promise delivery',async()=>{await mount();await press(enable());expect(native.PalateVisitMonitor.startMonitoring).toHaveBeenCalledTimes(1);expect(text()).toContain('Background checks started');expect(text()).toContain('Some stops may be missed');expect(text()).toContain('Dish details are optional');expect(text()).toContain('notification permission');await press(button('Continue'));expect(mockReplace).toHaveBeenCalledWith('/onboarding/done')});
test.each([['flag-off','temporarily unavailable'],['native-module-unavailable','does not support']])('%s retains choice without claiming startup',async(reason,copy)=>{if(reason==='flag-off')(isFlagEnabled as jest.Mock).mockResolvedValue(false);else native.isVisitMonitorAvailable=false;await mount();await press(enable());expect(await AsyncStorage.getItem('palate.passive.optIn')).toBe('1');expect(text()).toContain(copy);expect(text()).not.toContain("You're set");expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test('permission revoked during flag wait gets repair, not success',async()=>{const p=deferred();(isFlagEnabled as jest.Mock).mockImplementation(()=>p.promise);await mount();act(()=>{void enable().props.onPress()});await flush();native.PalateVisitMonitor.authorizationStatus.mockReturnValue('whenInUse');await act(async()=>p.resolve(true));await flush();expect(text()).toContain('Allow Always');expect(button('Open iOS Settings')).toBeDefined();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test('opt-out during start stays off even after explicit retry',async()=>{const p=deferred();(isFlagEnabled as jest.Mock).mockImplementationOnce(()=>p.promise);await mount();act(()=>{void enable().props.onPress()});await flush();await setPassiveOptIn(false);await act(async()=>p.resolve(true));await flush();expect(text()).toContain('cancelled or consent is off');await press(button('Retry background check'));expect(await AsyncStorage.getItem('palate.passive.optIn')).toBe('0');expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test('flag recovery retry starts once without rewriting consent timestamp',async()=>{(isFlagEnabled as jest.Mock).mockResolvedValue(false);await mount();await press(enable());(AsyncStorage.setItem as jest.Mock).mockClear();(isFlagEnabled as jest.Mock).mockResolvedValue(true);await press(button('Retry background check'));expect(native.PalateVisitMonitor.startMonitoring).toHaveBeenCalledTimes(1);expect(AsyncStorage.setItem).not.toHaveBeenCalled()});
test.each(['palate.passive.optIn','palate.passive.optInAt'])('failed %s write remains uncertain and does not navigate away',async key=>{(AsyncStorage.setItem as jest.Mock).mockImplementation((k,v)=>k===key?Promise.reject(Error('disk')):originalSet(k,v));await mount();await press(enable());expect(text()).toContain("couldn't confirm");expect(mockReplace).not.toHaveBeenCalled();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled();expect(button('Retry background check')).toBeDefined()});
test('native start throws after consent: distinguish saved from confirmed running',async()=>{native.PalateVisitMonitor.startMonitoring.mockImplementation(()=>{throw Error('bridge')});await mount();await press(enable());expect(text()).toContain('Your preference was saved');expect(text()).toContain("couldn't confirm whether");expect(mockReplace).not.toHaveBeenCalled()});
test('same-turn repeat admits one permission and start sequence',async()=>{const p=deferred();(ensureNotificationPermission as jest.Mock).mockImplementation(()=>p.promise);await mount();const cb=enable().props.onPress;act(()=>{void cb();void cb()});await flush();expect(ensureNotificationPermission).toHaveBeenCalledTimes(1);await act(async()=>p.resolve(false));await flush();expect(native.PalateVisitMonitor.startMonitoring).toHaveBeenCalledTimes(1)});
test.each(['unmount','blur'])('late permission completion after %s cannot save consent or start',async how=>{const p=deferred();(ensureNotificationPermission as jest.Mock).mockImplementation(()=>p.promise);await mount();act(()=>{void enable().props.onPress()});await flush();if(how==='unmount'){await act(async()=>tree.unmount());tree=null}else await focus(false);await act(async()=>p.resolve(false));await flush();expect(await AsyncStorage.getItem('palate.passive.optIn')).toBeNull();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test('old completion cannot clear newer operation after blur/refocus',async()=>{const p=deferred(),q=deferred();(ensureNotificationPermission as jest.Mock).mockImplementationOnce(()=>p.promise).mockImplementationOnce(()=>q.promise);await mount();act(()=>{void enable().props.onPress()});await flush();await focus(false);await focus(true);act(()=>{void enable().props.onPress()});await flush();await act(async()=>p.resolve(false));await flush();expect(enable().props.loading).toBe(true);expect(await AsyncStorage.getItem('palate.passive.optIn')).toBeNull();await act(async()=>q.resolve(false));await flush();expect(native.PalateVisitMonitor.startMonitoring).toHaveBeenCalledTimes(1)});
test('disclosure describes pre-confirmation lookup and sync, foreground intro separates optional background choice',async()=>{await mount();await act(async()=>tree.root.findByType('Pressable').props.onPress());expect(text()).toContain("stop's location");expect(text()).toContain('before you confirm');expect(text()).not.toContain('never leaves');expect(text()).toContain('does not tell Palate what you ordered');await act(async()=>tree.update(<WhyLocation/>));expect(text()).toContain('separate, optional choice');expect(text()).not.toContain('nothing new is recorded')});
test('return from phone Settings never auto-enables; explicit check remains available',async()=>{native.isVisitMonitorAvailable=false;const loc=jest.requireMock('expo-location');loc.getBackgroundPermissionsAsync.mockResolvedValue({status:'denied'});await mount();await press(enable());expect(text()).toContain('Background permission is needed');await press(button('Open iOS Settings'));await focus(false);loc.getBackgroundPermissionsAsync.mockResolvedValue({status:'granted'});await focus(true);expect(await AsyncStorage.getItem('palate.passive.optIn')).toBeNull();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled();await press(button('Check permission and enable'));expect(await AsyncStorage.getItem('palate.passive.optIn')).toBe('1');expect(text()).toContain('does not support')});
test('failed Settings link stays recoverable without unhandled rejection',async()=>{native.isVisitMonitorAvailable=false;const loc=jest.requireMock('expo-location');loc.getBackgroundPermissionsAsync.mockResolvedValue({status:'denied'});(Linking.openSettings as jest.Mock).mockRejectedValue(Error('unavailable'));await mount();await press(enable());await press(button('Open iOS Settings'));expect(button('Open iOS Settings').props.loading).toBe(false);expect(button('Continue without enabling')).toBeDefined();expect(await AsyncStorage.getItem('palate.passive.optIn')).toBeNull();loc.getBackgroundPermissionsAsync.mockResolvedValue({status:'granted'})});

test('Not now exits without requesting permission, writing consent, or starting',async()=>{await mount();await press(button('Not now'));expect(mockReplace).toHaveBeenCalledWith('/onboarding/done');expect(ensureNotificationPermission).not.toHaveBeenCalled();expect(await AsyncStorage.getItem('palate.passive.optIn')).toBeNull();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test('foreground denial preserves manual continuation and never opts in',async()=>{native.PalateVisitMonitor.authorizationStatus.mockReturnValue('denied');await mount();await press(enable());expect(mockReplace).toHaveBeenCalledWith('/onboarding/done');expect(await AsyncStorage.getItem('palate.passive.optIn')).toBeNull();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
