import React from "react";
const {create,act}=require("react-test-renderer");
import AsyncStorage from "@react-native-async-storage/async-storage";
import {Linking} from "react-native";
import {PassiveCaptureToggle} from "../../components/PassiveCaptureToggle";
import {setUsernameGateAccount,__resetUsernameGate} from "../username-gate";
import {readFlag,isFlagEnabled} from "../flags";
import * as Location from "expo-location";
const mockPush=jest.fn(),mockListeners=new Set<()=>void>(),mockActive=new Set<(state:string)=>void>();let mockFocus=true;
jest.mock("expo-router",()=>({useRouter:()=>({push:mockPush}),useFocusEffect:(cb:any)=>require("react").useEffect(()=>mockFocus?cb():undefined,[cb,mockFocus])}));
jest.mock("react-native",()=>({View:"View",Switch:"Switch",StyleSheet:{create:(x:any)=>x},Linking:{openSettings:jest.fn(async()=>{})},AppState:{addEventListener:(_event:string,cb:(s:string)=>void)=>{mockActive.add(cb);return{remove:()=>mockActive.delete(cb)}}}}));
jest.mock("../../components/Text",()=>({Text:"Text"}));
jest.mock("../../components/Button",()=>({Button:"Button",Spacer:()=>null}));
jest.mock("../../theme",()=>({colors:{},type:{body:{},small:{}}}));
jest.mock("../personal-signal",()=>({onPersonalSignalInvalidate:(cb:()=>void)=>{mockListeners.add(cb);return()=>mockListeners.delete(cb)}}));
jest.mock("../flags",()=>({readFlag:jest.fn(async()=>true),isFlagEnabled:jest.fn(async()=>true)}));
jest.mock("../analytics",()=>({track:jest.fn()}));
jest.mock("../../modules/palate-visit-monitor",()=>({isVisitMonitorAvailable:true,PalateVisitMonitor:{authorizationStatus:jest.fn(()=>"always"),startMonitoring:jest.fn(),stopMonitoring:jest.fn()}}));
jest.mock("expo-location",()=>({getForegroundPermissionsAsync:jest.fn(async()=>({status:"granted"})),getBackgroundPermissionsAsync:jest.fn(async()=>({status:"granted"})),requestForegroundPermissionsAsync:jest.fn(),requestBackgroundPermissionsAsync:jest.fn()}));
// Real passive-capture and passive-permissions; mocks only storage/OS/remote boundaries.
Object.defineProperty(globalThis,"fetch",{configurable:true,value:()=>{throw Error("Network forbidden")}});
const native=jest.requireMock("../../modules/palate-visit-monitor");
const KEY="palate.passive.optIn",STAMP="palate.passive.optInAt";
const originalGet=(AsyncStorage.getItem as jest.Mock).getMockImplementation()!,originalSet=(AsyncStorage.setItem as jest.Mock).getMockImplementation()!;
let tree:any;
const defer=()=>{let resolve!:(v:any)=>void,reject!:(v:any)=>void;const promise=new Promise((r,j)=>{resolve=r;reject=j});return{promise,resolve,reject}};
const content=()=>JSON.stringify(tree.toJSON());
const toggle=()=>tree.root.findByType("Switch");
const button=(title:string)=>tree.root.findAllByType("Button").find((x:any)=>x.props.title===title);
async function flush(){await act(async()=>{for(let i=0;i<16;i++)await Promise.resolve()})}
async function mount(strict=false){await act(async()=>{tree=create(strict?<React.StrictMode><PassiveCaptureToggle/></React.StrictMode>:<PassiveCaptureToggle/>)});await flush()}
async function change(next:boolean){await act(async()=>toggle().props.onValueChange(next));await flush()}
async function focus(v:boolean){mockFocus=v;await act(async()=>tree.update(<PassiveCaptureToggle/>));await flush()}
async function active(){await act(async()=>{for(const cb of mockActive)cb("active")});await flush()}
async function press(title:string){await act(async()=>button(title).props.onPress());await flush()}
async function resolve(p:any,v:any){await act(async()=>p.resolve(v));await flush()}
beforeEach(async()=>{jest.restoreAllMocks();jest.clearAllMocks();(AsyncStorage.getItem as jest.Mock).mockReset().mockImplementation(originalGet);(AsyncStorage.setItem as jest.Mock).mockReset().mockImplementation(originalSet);await AsyncStorage.clear();__resetUsernameGate();setUsernameGateAccount("A");mockFocus=true;native.isVisitMonitorAvailable=true;native.PalateVisitMonitor.authorizationStatus.mockReset().mockReturnValue("always");native.PalateVisitMonitor.startMonitoring.mockReset();native.PalateVisitMonitor.stopMonitoring.mockReset();(readFlag as jest.Mock).mockReset().mockResolvedValue(true);(isFlagEnabled as jest.Mock).mockReset().mockResolvedValue(true);});
afterEach(async()=>{if(tree)await act(async()=>tree.unmount());tree=null;mockListeners.clear();mockActive.clear();expect(Location.requestForegroundPermissionsAsync).not.toHaveBeenCalled();expect(Location.requestBackgroundPermissionsAsync).not.toHaveBeenCalled()});

test("first load is unknown, never assumed off or auto-started",async()=>{const p=defer();(AsyncStorage.getItem as jest.Mock).mockImplementationOnce(()=>p.promise);await mount();expect(content()).toContain("Loading");expect(tree.root.findAllByType("Switch")).toHaveLength(0);expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled();await resolve(p,"0");expect(toggle().props.value).toBe(false)});
test.each(["throw","corrupt"])("unreadable opt-in %s has retry, no false-off",async mode=>{if(mode==="throw")(AsyncStorage.getItem as jest.Mock).mockRejectedValueOnce(Error("read"));else await AsyncStorage.setItem(KEY,"bad");await mount();expect(content()).toContain("couldn’t read your saved choice");expect(tree.root.findAllByType("Switch")).toHaveLength(0);await AsyncStorage.setItem(KEY,"1");await press("Check again");expect(toggle().props.value).toBe(true)});
test("saved on with missing Always stays on and can opt out",async()=>{await AsyncStorage.setItem(KEY,"1");native.PalateVisitMonitor.authorizationStatus.mockReturnValue("whenInUse");await mount();expect(toggle().props.value).toBe(true);expect(toggle().props.disabled).toBe(false);expect(content()).toContain("Always location");await change(false);expect(await AsyncStorage.getItem(KEY)).toBe("0");expect(native.PalateVisitMonitor.stopMonitoring).toHaveBeenCalledTimes(1);expect(toggle().props.value).toBe(false)});
test.each(["permission","flag"])("unknown %s does not prevent revoking known consent",async which=>{await AsyncStorage.setItem(KEY,"1");if(which==="permission")native.PalateVisitMonitor.authorizationStatus.mockImplementation(()=>{throw Error("read")});else{(readFlag as jest.Mock).mockResolvedValue(null);(isFlagEnabled as jest.Mock).mockResolvedValue(false);}await mount();expect(toggle().props.value).toBe(true);expect(toggle().props.disabled).toBe(false);await change(false);expect(await AsyncStorage.getItem(KEY)).toBe("0")});
test("remote-off still shows stored consent and permits off",async()=>{await AsyncStorage.setItem(KEY,"1");(readFlag as jest.Mock).mockResolvedValue(false);(isFlagEnabled as jest.Mock).mockResolvedValue(false);await mount();expect(toggle().props.value).toBe(true);await change(false);expect(await AsyncStorage.getItem(KEY)).toBe("0");expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test("off and verified remote-off remains hidden",async()=>{(readFlag as jest.Mock).mockResolvedValue(false);(isFlagEnabled as jest.Mock).mockResolvedValue(false);await mount();expect(tree.toJSON()).toBe(null)});
test.each(["permission","flag"])("unknown %s cannot enable",async which=>{if(which==="permission")native.PalateVisitMonitor.authorizationStatus.mockReturnValue("unknown");else{(readFlag as jest.Mock).mockResolvedValue(null);(isFlagEnabled as jest.Mock).mockResolvedValue(false);}await mount();expect(toggle().props.disabled).toBe(true);await change(true);expect(await AsyncStorage.getItem(KEY)).toBe(null);expect(mockPush).not.toHaveBeenCalled();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test("missing permission enters intro once without consent write; return reloads",async()=>{native.PalateVisitMonitor.authorizationStatus.mockReturnValue("whenInUse");await mount();const cb=toggle().props.onValueChange;await act(async()=>{cb(true);cb(true)});expect(mockPush).toHaveBeenCalledTimes(1);expect(mockPush).toHaveBeenCalledWith("/passive-capture-intro");expect(await AsyncStorage.getItem(KEY)).toBe(null);await focus(false);await AsyncStorage.setItem(KEY,"1");native.PalateVisitMonitor.authorizationStatus.mockReturnValue("always");await focus(true);expect(toggle().props.value).toBe(true);expect(content()).toContain("Location access is allowed")});
test("phone settings repair and foreground return only read",async()=>{await AsyncStorage.setItem(KEY,"1");native.PalateVisitMonitor.authorizationStatus.mockReturnValue("whenInUse");await mount();await press("Review phone location settings");expect(Linking.openSettings).toHaveBeenCalledTimes(1);native.PalateVisitMonitor.authorizationStatus.mockReturnValue("always");await active();expect(content()).toContain("Location access is allowed");expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test("failed phone settings open is visible and retryable",async()=>{await AsyncStorage.setItem(KEY,"1");native.PalateVisitMonitor.authorizationStatus.mockReturnValue("whenInUse");(Linking.openSettings as jest.Mock).mockRejectedValueOnce(Error("open"));await mount();await press("Review phone location settings");expect(content()).toContain("Couldn’t open phone settings");await press("Review phone location settings");expect(Linking.openSettings).toHaveBeenCalledTimes(2)});
test("explicit enable with permission persists then calls actual startup",async()=>{await mount();await change(true);expect(await AsyncStorage.getItem(KEY)).toBe("1");expect(native.PalateVisitMonitor.startMonitoring).toHaveBeenCalledTimes(1);expect(content()).toContain("Background checks were requested");expect(toggle().props.value).toBe(true)});
test.each(["flag-off","native-module-unavailable","no-always-permission"])("actual startup result %s is not a running claim",async reason=>{await mount();if(reason==="flag-off")(isFlagEnabled as jest.Mock).mockResolvedValue(false);if(reason==="native-module-unavailable")native.isVisitMonitorAvailable=false;if(reason==="no-always-permission")native.PalateVisitMonitor.authorizationStatus.mockReturnValue("whenInUse");await change(true);expect(await AsyncStorage.getItem(KEY)).toBe("1");expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled();expect(content()).not.toContain("Background checks were requested");expect(content()).toContain(reason==="flag-off"?"paused":reason==="native-module-unavailable"?"not available in this version":"Always location access")});
test("double toggle and opposite old callback admit one save",async()=>{await mount();const p=defer();(AsyncStorage.setItem as jest.Mock).mockImplementationOnce(()=>p.promise);const cb=toggle().props.onValueChange;const before=(AsyncStorage.setItem as jest.Mock).mock.calls.length;await act(async()=>{cb(true);cb(true);cb(false)});expect((AsyncStorage.setItem as jest.Mock).mock.calls.length-before).toBe(1);expect(toggle().props.disabled).toBe(true);await resolve(p,undefined)});
test("off write failure keeps actual stored value and offers explicit retry",async()=>{await AsyncStorage.setItem(KEY,"1");await mount();(AsyncStorage.setItem as jest.Mock).mockRejectedValueOnce(Error("write"));await change(false);expect(toggle().props.value).toBe(true);expect(native.PalateVisitMonitor.stopMonitoring).not.toHaveBeenCalled();expect(content()).toContain("couldn’t confirm background checks stopped");await press("Try turning off again");expect(await AsyncStorage.getItem(KEY)).toBe("0");expect(native.PalateVisitMonitor.stopMonitoring).toHaveBeenCalledTimes(1)});
test("native stop failure after saved off stays honest; same-value retry works",async()=>{await AsyncStorage.setItem(KEY,"1");await mount();native.PalateVisitMonitor.stopMonitoring.mockImplementationOnce(()=>{throw Error("stop")});await change(false);expect(toggle().props.value).toBe(false);expect(content()).toContain("couldn’t confirm background checks stopped");await press("Try turning off again");expect(native.PalateVisitMonitor.stopMonitoring).toHaveBeenCalledTimes(2)});
test("partial opt-in timestamp failure reads saved consent without starting",async()=>{await mount();(AsyncStorage.getItem as jest.Mock).mockImplementation((key:string)=>key===STAMP?Promise.reject(Error("stamp")):originalGet(key));await change(true);expect(toggle().props.value).toBe(true);expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled();expect(content()).toContain("couldn’t finish turning this on")});
test("stale initial read cannot overwrite foreground result",async()=>{const old=defer();(AsyncStorage.getItem as jest.Mock).mockImplementationOnce(()=>old.promise);await mount();await AsyncStorage.setItem(KEY,"1");await active();expect(toggle().props.value).toBe(true);await resolve(old,"0");expect(toggle().props.value).toBe(true)});
test("pending read rejects retained toggle callback",async()=>{await mount();const cb=toggle().props.onValueChange;const p=defer();(AsyncStorage.getItem as jest.Mock).mockImplementationOnce(()=>p.promise);await active();await act(async()=>cb(true));expect(await AsyncStorage.getItem(KEY)).toBe(null);expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled();await resolve(p,"0")});
test("old render callback cannot write after completed refresh",async()=>{await mount();const cb=toggle().props.onValueChange;await active();await act(async()=>cb(true));expect(await AsyncStorage.getItem(KEY)).toBe(null)});
test.each(["B","ABA",null])("account %s during consent save prevents later startup",async next=>{await mount();const p=defer();(AsyncStorage.setItem as jest.Mock).mockImplementationOnce(()=>p.promise);await change(true);await act(async()=>{setUsernameGateAccount(next==="ABA"?"B":next);if(next==="ABA")setUsernameGateAccount("A");for(const cb of mockListeners)cb()});await resolve(p,undefined);expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test("blur during save skips startup and refocus waits for write settlement",async()=>{await mount();const p=defer();(AsyncStorage.setItem as jest.Mock).mockImplementationOnce(()=>p.promise);await change(true);await focus(false);await focus(true);expect(toggle().props.disabled).toBe(true);await resolve(p,undefined);expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled();expect(toggle().props.disabled).toBe(false)});
test("unmount after save starts rejects retained callbacks and later startup",async()=>{await mount();const p=defer();(AsyncStorage.setItem as jest.Mock).mockImplementationOnce(()=>p.promise);const cb=toggle().props.onValueChange;await change(true);await act(async()=>tree.unmount());tree=null;await act(async()=>{cb(false);p.resolve(undefined)});await flush();expect(native.PalateVisitMonitor.startMonitoring).not.toHaveBeenCalled()});
test("blur rejects retained switch and repair actions",async()=>{await AsyncStorage.setItem(KEY,"1");native.PalateVisitMonitor.authorizationStatus.mockReturnValue("whenInUse");await mount();const cb=toggle().props.onValueChange,repair=button("Review phone location settings").props.onPress;await focus(false);await act(async()=>{cb(false);repair()});expect(await AsyncStorage.getItem(KEY)).toBe("1");expect(Linking.openSettings).not.toHaveBeenCalled()});
test("null account neither reads flag nor writes",async()=>{setUsernameGateAccount(null);await mount();expect(readFlag).not.toHaveBeenCalled();expect(await AsyncStorage.getItem(KEY)).toBe(null);expect(content()).toContain("account is ready")});
test("StrictMode replay discards abandoned status",async()=>{const old=defer();(AsyncStorage.getItem as jest.Mock).mockImplementationOnce(()=>old.promise);await mount(true);expect(toggle().props.value).toBe(false);await resolve(old,"1");expect(toggle().props.value).toBe(false)});
