jest.mock('@react-native-async-storage/async-storage',()=>{const data=new Map<string,string>();return{__esModule:true,default:{getItem:jest.fn(async(k:string)=>data.get(k)??null),setItem:jest.fn(async(k:string,v:string)=>{data.set(k,v)}),clear:async()=>data.clear()}}});
jest.mock('../flags',()=>({isFlagEnabled:jest.fn(async()=>true)}));
jest.mock('../../modules/palate-visit-monitor',()=>({isVisitMonitorAvailable:true,PalateVisitMonitor:{startMonitoring:jest.fn(),stopMonitoring:jest.fn(),authorizationStatus:jest.fn(()=> 'always')}}));
let api:any,store:any,flag:any,native:any;
const KEY='palate.passive.optIn',AT='palate.passive.optInAt';
function deferred(){let resolve!:(x?:any)=>void;const promise=new Promise<any>(r=>resolve=r);return{resolve,promise}}
beforeEach(()=>{jest.resetModules();api=require('../passive-capture');store=require('@react-native-async-storage/async-storage').default;flag=require('../flags').isFlagEnabled;native=require('../../modules/palate-visit-monitor').PalateVisitMonitor});
async function ticks(){for(let i=0;i<30;i++)await Promise.resolve()}
test('fresh resume remains possible after debug stop interrupts an enable write',async()=>{const entered=deferred(),release=deferred(),set=store.setItem.getMockImplementation();store.setItem.mockImplementationOnce(async(k:string,v:string)=>{entered.resolve();await release.promise;await set(k,v)});const enable=api.setPassiveOptIn(true);await entered.promise;const old=api.startPassiveCaptureIfEnabled();api.stopPassiveCapture();release.resolve();await enable;expect(await old).toMatchObject({started:false});expect(await store.getItem(KEY)).toBe('1');expect(await api.resumePassiveCaptureIfOptedIn()).toEqual({started:true});expect(native.startMonitoring).toHaveBeenCalledTimes(1)});
test('failed enable interrupted by debug stop stays blocked',async()=>{const entered=deferred(),release=deferred();store.setItem.mockImplementationOnce(async()=>{entered.resolve();await release.promise;throw Error('disk')});const enable=api.setPassiveOptIn(true);void enable.catch(()=>{});await entered.promise;api.stopPassiveCapture();release.resolve();await expect(enable).rejects.toThrow();expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({started:false});expect(native.startMonitoring).not.toHaveBeenCalled()});
test('on off on concurrent intents persist in order and only latest explicit on enables',async()=>{const entered=deferred(),release=deferred(),set=store.setItem.getMockImplementation();store.setItem.mockImplementationOnce(async(k:string,v:string)=>{entered.resolve();await release.promise;await set(k,v)});const one=api.setPassiveOptIn(true);await entered.promise;const old=api.startPassiveCaptureIfEnabled();const off=api.setPassiveOptIn(false);const latest=api.setPassiveOptIn(true);expect(native.stopMonitoring).toHaveBeenCalledTimes(1);release.resolve();await Promise.all([one,off,latest]);expect(await old).toMatchObject({started:false});expect(await store.getItem(KEY)).toBe('1');expect(await api.startPassiveCaptureIfEnabled()).toEqual({started:true})});
test('direct false setter revokes while strict consent read is pending',async()=>{const entered=deferred(),release=deferred();store.getItem.mockImplementationOnce(()=>{entered.resolve();return release.promise});const start=api.startPassiveCaptureIfEnabled();await entered.promise;await api.setPassiveOptIn(false);release.resolve('1');expect(await start).toMatchObject({started:false});expect(flag).not.toHaveBeenCalled();expect(native.startMonitoring).not.toHaveBeenCalled()});
test('flag rejection recovers queue for a fresh start',async()=>{await store.setItem(KEY,'1');flag.mockRejectedValueOnce(Error('flag'));await expect(api.startPassiveCaptureIfEnabled()).rejects.toThrow('flag');expect(await api.startPassiveCaptureIfEnabled()).toEqual({started:true})});
test('native start throw rejects without poisoning later starts',async()=>{await store.setItem(KEY,'1');native.startMonitoring.mockImplementationOnce(()=>{throw Error('bridge')});await expect(api.startPassiveCaptureIfEnabled()).rejects.toThrow('bridge');expect(await api.startPassiveCaptureIfEnabled()).toEqual({started:true})});
test('both off failures surface error and retain runtime block',async()=>{await store.setItem(KEY,'1');native.stopMonitoring.mockImplementationOnce(()=>{throw Error('stop')});store.setItem.mockRejectedValueOnce(Error('storage'));await expect(api.optOutOfPassiveCapture()).rejects.toThrow('storage');expect(await store.getItem(KEY)).toBe('1');expect(await api.startPassiveCaptureIfEnabled()).toMatchObject({started:false})});
test('documented limit: fresh explicit start waits behind hung old flag, but off persists',async()=>{await store.setItem(KEY,'1');const entered=deferred(),release=deferred();flag.mockImplementationOnce(()=>{entered.resolve();return release.promise});const old=api.startPassiveCaptureIfEnabled();await entered.promise;await api.optOutOfPassiveCapture();expect(await store.getItem(KEY)).toBe('0');await api.setPassiveOptIn(true);let settled=false;const fresh=api.startPassiveCaptureIfEnabled().then((x:any)=>{settled=true;return x});await ticks();expect(settled).toBe(false);expect(native.startMonitoring).not.toHaveBeenCalled();release.resolve(true);expect(await old).toMatchObject({started:false});expect(await fresh).toEqual({started:true})});
