const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const mobile=process.env.PALATE_MOBILE||path.resolve(__dirname,'..'),deps=path.join(mobile,'node_modules'),ts=require(path.join(deps,'typescript'));
global.fetch=()=>{throw Error('Real network prohibited')};const{createClient}=require(path.join(deps,'@supabase/supabase-js'));
const root=process.env.SOURCE_ROOT||(fs.existsSync(path.join(__dirname,'source'))?path.join(__dirname,'source'):path.join(mobile,'lib')),defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve}};
const entry={id:'entry-A',place_id:'place',name:'Synthetic',address:'',alternates:[],detectedAt:Date.now(),dwellMin:15,stopLat:33,stopLng:44};
function harness(config={}){let ready=false,current='A',sdkCalls=0,localReads=0;const calls=[],writes=[],effects=[],store=new Map(),gates=new Map((config.pause||[]).map(s=>[s,{entered:defer(),release:defer()}]));
 const step=async s=>{const g=gates.get(s);if(g){g.entered.resolve();await g.release.promise}};
 const client=createClient('https://synthetic.invalid','synthetic-key',{accessToken:async()=>{if(ready)await step('sdk:'+ ++sdkCalls);return 'token-'+current},auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false},global:{fetch:async(input,init)=>{const u=new URL(input),method=init.method,stage=method==='GET'?'hydrate':method==='POST'?'upsert':'delete';calls.push({stage,method,query:u.search,body:init.body?JSON.parse(init.body):null,authorization:new Headers(init.headers).get('Authorization')});await step(stage);if(config.error===stage)return new Response(JSON.stringify({message:'injected error'}),{status:400});return new Response(method==='GET'?JSON.stringify([{payload:entry}]):'',{status:method==='GET'?200:201})}}});
 ready=true;
 const supabase={from:client.from.bind(client),auth:{getUser:async()=>{await step('user');return{data:{user:config.noUser?null:{id:config.user||current}},error:config.error==='user'?Error('user error'):null}},getSession:async()=>{await step('session');return{data:{session:config.noSession?null:{user:{id:config.sessionUser||current},access_token:'token-'+current}},error:config.error==='session'?Error('session error'):null}}}};
 const storage={getItem:async k=>{if(k==='palate.passive.inbox'){await step('local:'+ ++localReads)}return store.get(k)??null},setItem:async(k,v)=>{await step('write');writes.push({k,v});store.set(k,v)},removeItem:async k=>store.delete(k)};
 const mocks={'./supabase':{supabase},'@react-native-async-storage/async-storage':{__esModule:true,default:storage},'expo-notifications':{},'./analytics':{track:async()=>effects.push('track')},'./observability':{captureError:async()=>{}},'./visits':{recentlyPrompted:async()=>false,placeRefusals:async()=>0,shouldDemote:()=>false},'./passive-digest':{scheduleDigest:async()=>effects.push('schedule'),DIGEST_NOTIF_ID_STORAGE_KEY:'digest'}};
 const cache={};function load(name){if(cache[name])return cache[name];const exports=cache[name]={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(path.join(root,name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,Date,console,require:id=>mocks[id]||load(id.slice(2))});return exports}
 const gate=load('username-gate');gate.setUsernameGateAccount('A');const sync=load('passive-inbox-sync'),confirm=load('passive-confirm');
 const change=kind=>{current=kind==='refresh'?'A':kind==='signout'?null:'B';gate.setUsernameGateAccount(current);if(kind==='ABA'){current='A';gate.setUsernameGateAccount('A')}};
 return{sync,confirm,gate,calls,writes,effects,store,change,entered:s=>gates.get(s).entered.promise,release:s=>gates.get(s).release.resolve()};
}
const T=(name,fn)=>test(name,{timeout:3000},fn);
for(const operation of ['mirror','empty','hydrate'])for(const stage of ['user','session'])for(const change of ['B','ABA','signout'])T(`${operation} refuses after ${change} during ${stage}`,async()=>{const h=harness({pause:[stage]});const p=operation==='hydrate'?h.sync.hydrateInboxIfEmpty(0):h.sync.mirrorInbox(operation==='empty'?[]:[entry]);await h.entered(stage);h.change(change);h.release(stage);await p;assert.equal(h.calls.length,0)});
for(const operation of ['mirror','empty','hydrate'])T(`${operation} pins Authorization at deferred SDK token boundary`,async()=>{const h=harness({pause:['sdk:1']});const p=operation==='hydrate'?h.sync.hydrateInboxIfEmpty(0):h.sync.mirrorInbox(operation==='empty'?[]:[entry]);await h.entered('sdk:1');h.change('B');h.release('sdk:1');const result=await p;assert.equal(h.calls.length,1);assert.equal(h.calls[0].authorization,'Bearer token-A');if(operation==='mirror')assert.equal(h.calls[0].body[0].user_id,'A');else assert(h.calls[0].query.includes('user_id=eq.A'));if(operation==='hydrate')assert.equal(result,null)});
for(const change of ['B','ABA','signout'])T(`upsert completion after ${change} cannot prune`,async()=>{const h=harness({pause:['upsert']});const p=h.sync.mirrorInbox([entry]);await h.entered('upsert');h.change(change);h.release('upsert');await p;assert.equal(h.calls.length,1)});
for(const change of ['B','ABA','signout'])T(`hydrate completion after ${change} returns no rows`,async()=>{const h=harness({pause:['hydrate']});const p=h.sync.hydrateInboxIfEmpty(0);await h.entered('hydrate');h.change(change);h.release('hydrate');assert.equal(await p,null)});
T('same-account refresh permits upsert then prune with pinned credentials and payload whitelist',async()=>{const h=harness({pause:['upsert']});const p=h.sync.mirrorInbox([entry]);await h.entered('upsert');h.change('refresh');h.release('upsert');await p;assert.equal(h.calls.length,2);for(const c of h.calls)assert.equal(c.authorization,'Bearer token-A');assert.equal(h.calls[0].body[0].payload.stopLat,undefined);assert.equal(h.calls[0].body[0].payload.stopLng,undefined);assert(h.calls[1].query.includes('user_id=eq.A'))});
for(const config of [{noUser:true},{noSession:true},{user:'B'},{sessionUser:'B'},{error:'user'},{error:'session'}])T('invalid initiating credentials refuse '+JSON.stringify(config),async()=>{const h=harness(config);await h.sync.mirrorInbox([entry]);assert.equal(await h.sync.hydrateInboxIfEmpty(0),null);assert.equal(h.calls.length,0)});
T('upsert HTTP error does not prune',async()=>{const h=harness({error:'upsert'});await h.sync.mirrorInbox([entry]);assert.equal(h.calls.length,1)});
T('successful restore writes once and schedules',async()=>{const h=harness();assert.equal(await h.confirm.restoreInboxFromServer(),1);assert.equal(h.writes.length,1);assert(h.effects.includes('schedule'))});
for(const stage of ['local:1','hydrate','local:2'])for(const change of ['B','ABA'])T(`restore ${stage} after ${change} cannot commit`,async()=>{const h=harness({pause:[stage]});const p=h.confirm.restoreInboxFromServer();await h.entered(stage);h.change(change);h.release(stage);assert.equal(await p,0);assert.equal(h.writes.length,0);assert(!h.effects.includes('schedule'))});
T('account changes while restore commit waits behind unrelated local read',async()=>{const h=harness({pause:['hydrate','local:2']});const p=h.confirm.restoreInboxFromServer();await h.entered('hydrate');const reader=h.confirm.getInbox();await h.entered('local:2');h.release('hydrate');for(let i=0;i<20;i++)await Promise.resolve();h.change('ABA');h.release('local:2');await reader;assert.equal(await p,0);assert.equal(h.writes.length,0)});
T('already-started local write may land but stale completion returns zero without scheduling',async()=>{const h=harness({pause:['write']});const p=h.confirm.restoreInboxFromServer();await h.entered('write');h.change('B');h.release('write');assert.equal(await p,0);assert.equal(h.writes.length,1);assert(!h.effects.includes('schedule'))});
T('restore same-account refresh during commit read stays valid',async()=>{const h=harness({pause:['local:2']});const p=h.confirm.restoreInboxFromServer();await h.entered('local:2');h.change('refresh');h.release('local:2');assert.equal(await p,1)});

T('prune pins original Authorization through its own deferred SDK lookup',async()=>{const h=harness({pause:['sdk:2']});const p=h.sync.mirrorInbox([entry]);await h.entered('sdk:2');h.change('B');h.release('sdk:2');await p;assert.equal(h.calls.length,2);assert.equal(h.calls[1].authorization,'Bearer token-A');assert(h.calls[1].query.includes('user_id=eq.A'))});

T('signed-out initiating context makes no personal request or local restore commit',async()=>{const h=harness();h.change('signout');await h.sync.mirrorInbox([entry]);assert.equal(await h.sync.hydrateInboxIfEmpty(0),null);assert.equal(await h.confirm.restoreInboxFromServer(),0);assert.equal(h.calls.length,0);assert.equal(h.writes.length,0)});
