-- ============================================================================
-- 0030_blurb_and_delete_policy.sql
-- ----------------------------------------------------------------------------
-- 1. Delete policy on restaurant_overrides so users can revert their own
--    cuisine correction from the detail screen. Without this, the "Revert"
--    button hits RLS and fails silently.
-- 2. Editorial blurb cache on restaurants — a one-sentence "what is this
--    place" generated by Haiku from review snippets, surfaced on the
--    detail screen. Cached per place_id; regenerated when reviews refresh.
-- ============================================================================

-- 1. Delete policy: only the user who submitted an override can revert it.
--    Subsequent corrections by other users overwrite via the unique
--    (restaurant_id, field) constraint, so this naturally allows the
--    most-recent corrector to undo their own change.
drop policy if exists "overrides creator delete" on public.restaurant_overrides;
create policy "overrides creator delete"
  on public.restaurant_overrides for delete
  to authenticated
  using (auth.uid() = user_id);

-- 2. Editorial blurb cache
alter table public.restaurants
  add column if not exists editorial_blurb text,
  add column if not exists editorial_blurb_generated_at timestamptz;

-- The resolved view inherits any new columns via `r.*` — recreate so PostgREST
-- exposes them. Definition matches 0028 + the new columns flowing through r.*.
create or replace view public.restaurants_resolved as
select
  r.*,
  coalesce(o_cuisine.value,    r.cuisine_type)      as resolved_cuisine_type,
  coalesce(o_subregion.value,  r.cuisine_subregion) as resolved_cuisine_subregion,
  coalesce(o_region.value,     r.cuisine_region)    as resolved_cuisine_region,
  coalesce(o_format.value,     r.format_class)      as resolved_format_class,
  coalesce(o_chain.value,      r.chain_type)        as resolved_chain_type
from public.restaurants r
left join public.restaurant_overrides o_cuisine
  on o_cuisine.restaurant_id = r.id and o_cuisine.field = 'cuisine_type'
left join public.restaurant_overrides o_subregion
  on o_subregion.restaurant_id = r.id and o_subregion.field = 'cuisine_subregion'
left join public.restaurant_overrides o_region
  on o_region.restaurant_id = r.id and o_region.field = 'cuisine_region'
left join public.restaurant_overrides o_format
  on o_format.restaurant_id = r.id and o_format.field = 'format_class'
left join public.restaurant_overrides o_chain
  on o_chain.restaurant_id = r.id and o_chain.field = 'chain_type';
